#include "PieceType.h"

const char *PIECE_TYPE_NAMES[14] = {
    "BRIDGE",
    "BRIDGE_CROSSING",
    "BRIDGE_SMALL_CROSSING",
    "BRIDGE_STAIRS",
    "BRIDGE_PLATFORM",
    "CORRIDOR_EXIT",
    "SMALL_CORRIDOR",
    "CORRIDOR_RIGHT_TURN",
    "CORRIDOR_LEFT_TURN",
    "CORRIDOR_STAIRS",
    "CORRIDOR_BALCONY",
    "CORRIDOR_CROSSING",
    "CORRIDOR_NETHER_WARTS_ROOM",
    "BRIDGE_END"
};